// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAIOJXfDQnseCYfhtbQAd38m0C72vW4g',
    appId: '1:954810824353:web:d9b0f36631c18d59b462e0',
    messagingSenderId: '954810824353',
    projectId: 'rafahedu-94f1d',
    authDomain: 'rafahedu-94f1d.firebaseapp.com',
    storageBucket: 'rafahedu-94f1d.appspot.com',
    measurementId: 'G-JE0VPJWSML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjoqfmoOszAf71yoAF_wFjfwCzn-fECg',
    appId: '1:954810824353:android:e1f3097df883c70db462e0',
    messagingSenderId: '954810824353',
    projectId: 'rafahedu-94f1d',
    storageBucket: 'rafahedu-94f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALn7hvGA7mAAjTQ2G54faRitxVii8b6V0',
    appId: '1:954810824353:ios:a69c68b9ebc0d693b462e0',
    messagingSenderId: '954810824353',
    projectId: 'rafahedu-94f1d',
    storageBucket: 'rafahedu-94f1d.appspot.com',
    iosClientId: '954810824353-4l82q5g3m8fvpeeom169fkfpkgue67h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafaheduapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALn7hvGA7mAAjTQ2G54faRitxVii8b6V0',
    appId: '1:954810824353:ios:a69c68b9ebc0d693b462e0',
    messagingSenderId: '954810824353',
    projectId: 'rafahedu-94f1d',
    storageBucket: 'rafahedu-94f1d.appspot.com',
    iosClientId: '954810824353-4l82q5g3m8fvpeeom169fkfpkgue67h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafaheduapp',
  );
}
